import matplotlib.pyplot as plt
import random

# plot the spikes generated by Poisson process which encode a value
def plot_spikes(spikes, T, width=900, height=20, padding=1): # Show a plot of the spikes
    fig, ax = plt.subplots(figsize=(width/100, height/100)) # Create a new figure
    spacing = (width - 2 * padding) / T # The factor to multiply spike time by to get an x position
    
    spike_width = 2
    spike_height = height - 2 * padding
    y = padding
    
    for t in spikes:
        x = padding + t * spacing
        rect = plt.Rectangle((x, y), spike_width, spike_height, color='black')
        ax.add_patch(rect)
    
    ax.set_xlim(0, width)
    ax.set_ylim(0, height)
    ax.axis('off')  # Turn off the axis

    plt.show()

# NB: in reality these would be generated on the fly not previously in a spikes array
# as this defeats the stateless appeal of them
# limits freq to 100 as dt=0.01
def poisson_spikes(freq, T, dt=0.01):
    spikes = []
    probFire = freq * dt
    numSteps = int(T / dt)
    for step in range(numSteps):
        if random.random() < probFire:
            t = step * dt
            spikes.append(t)
    return spikes, T

# scaling required to allow encoding negative values and to enforce constraints
def scaled_poission_spikes(val, val_min=0, val_max=100, f_min=0.9, f_max=10, T=100, dt=0.01):
    return poisson_spikes(f_min + (val - val_min) / (val_max - val_min) * (f_max - f_min), T, dt)

val = 25 # value we want to encode into a Poisson spiking process
v_min = 0 
v_max = 100
# this frequency range is pretty low so it will lose some accuracy :( but plots nicely <- in practice use higher f_max
f_min = 0 # min firing rate (must be >= 0)
f_max = 1 # max firing raate <- recall limited to 100
spikes, T = scaled_poission_spikes(val=val, val_min=v_min, val_max=v_max, f_min=f_min, f_max=f_max)
plot_spikes(spikes, T)
estimated_value = len(spikes) / T * (v_max - v_min) / (f_max - f_min) + v_min
print(f"Spikes: {len(spikes)} over {T} seconds ({len(spikes) / T:.2f} Hz). Estimated Value: {estimated_value:.2f} (Actual: {val}; Error: {abs(val - estimated_value):.2f})")