import matplotlib.pyplot as plt
import random
import numpy as np

# plot the spikes generated by Poisson process which encode a value
def plot_spikes(spikes, T, width=900, height=20, padding=1): # Show a plot of the spikes
    fig, ax = plt.subplots(figsize=(width/100, height/100)) # Create a new figure
    spacing = (width - 2 * padding) / T # The factor to multiply spike time by to get an x position
    
    spike_width = 2
    spike_height = height - 2 * padding
    y = padding
    
    for t in spikes:
        x = padding + t * spacing
        rect = plt.Rectangle((x, y), spike_width, spike_height, color='black')
        ax.add_patch(rect)
    
    ax.set_xlim(0, width)
    ax.set_ylim(0, height)
    ax.axis('off')  # Turn off the axis

    plt.show()

# NB: in reality these would be generated on the fly not previously in a spikes array
# as this defeats the stateless appeal of them
# limits freq to 100 as dt=0.01
def poisson_spikes(freq, T, dt=0.01):
    spikes = []
    probFire = freq * dt
    numSteps = int(T / dt)
    for step in range(numSteps):
        if random.random() < probFire:
            t = step * dt
            spikes.append(t)
    return spikes, T

# scaling required to allow encoding negative values and to enforce constraints
def scaled_poission_spikes(val, val_min=0, val_max=100, f_min=0.9, f_max=10, T=100, dt=0.01):
    return poisson_spikes(f_min + (val - val_min) / (val_max - val_min) * (f_max - f_min), T, dt)

# encode an integer into spiking pattern using probabilistic frequency encoding
def integer_encoding():
    val = 25 # value we want to encode into a Poisson spiking process
    v_min = 0 
    v_max = 100
    # this frequency range is pretty low so it will lose some accuracy :( but plots nicely <- in practice use higher f_max
    f_min = 0 # min firing rate (must be >= 0)
    f_max = 1 # max firing raate <- recall limited to 100
    spikes, T = scaled_poission_spikes(val=val, val_min=v_min, val_max=v_max, f_min=f_min, f_max=f_max)
    plot_spikes(spikes, T)
    estimated_value = len(spikes) / T * (v_max - v_min) / (f_max - f_min) + v_min
    print(f"Spikes: {len(spikes)} over {T} seconds ({len(spikes) / T:.2f} Hz). Estimated Value: {estimated_value:.2f} (Actual: {val}; Error: {abs(val - estimated_value):.2f})")


# encode 2D image into spiking pattern using probabilistic frequency encoding
def image_encoding():
    def poisson_fire(values, min_value=0, max_value=255, min_rate=0, max_rate=10, dt=0.001):
        relativeValues    = [ (v - min_value) / (max_value - min_value) for v in values ] # Normalize values to [0, 1]
        relativeRates     = [ min_rate + v * (max_rate - min_rate) for v in relativeValues ] # Scale rates to [min_rate, max_rate]
        probabilityOfFire = [ r * dt for r in relativeRates ] # Probability of firing in each time step

        firings = [random.random() < p for p in probabilityOfFire] # Generate random firing events

        return firings

    im = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 57, 8, 0, 0, 20, 62, 0, 0, 0, 0, 0, 0, 0, 16, 185, 63, 0, 0, 75, 157, 0, 0, 0, 0, 0, 0, 2, 109, 188, 19, 0, 4, 169, 108, 0, 0, 0, 0, 0, 0, 47, 196, 56, 0, 0, 56, 220, 49, 0, 0, 0, 0, 0, 5, 134, 109, 1, 0, 0, 127, 176, 12, 0, 0, 0, 0, 0, 70, 205, 24, 0, 0, 11, 208, 91, 0, 4, 6, 0, 0, 0, 77, 199, 40, 0, 0, 79, 228, 54, 34, 138, 41, 0, 0, 0, 40, 199, 222, 140, 123, 186, 240, 225, 190, 94, 3, 0, 0, 0, 0, 31, 132, 159, 159, 243, 202, 86, 25, 2, 0, 0, 0, 0, 0, 0, 0, 0, 11, 231, 109, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 173, 89, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 59, 49, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

    num_firings = [0] * len(im) # poisson processes (one for each pixel)

    # run it 1000 times and count number of times each 'neurone'/pixel fired 
    for i in range(1000):
        firings = poisson_fire(im, max_rate=100)
        for j in range(len(im)):
            if firings[j]:
                num_firings[j] += 1
    
    plt.figure()
    # plot im as a 14x14 matrix
    plt.imshow(np.reshape(im, (14, 14)), cmap='gray_r')
    plt.axis('off')
    plt.show()


if __name__ == "__main__":
    # integer_encoding()
    image_encoding()